# Generated by Django 5.2.12 on 2026-06-25 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cu9_gestionar_categorias', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, verbose_name='Nombre de Promoción')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('descuento_pct', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Descuento (%)')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de Fin')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Promoción',
                'verbose_name_plural': 'Promociones',
                'db_table': 'app_negocio_promocion',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('sku', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('costo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Costo de Compra')),
                ('stock', models.IntegerField(default=0)),
                ('atributos', models.JSONField(blank=True, default=dict, null=True, verbose_name='Atributos (Color, Talla, etc.)')),
                ('activo', models.BooleanField(default=True)),
                ('imagen_url', models.URLField(blank=True, max_length=500, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='productos', to='cu9_gestionar_categorias.categoria', verbose_name='Categoría')),
                ('promocion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='cu7_gestionar_productos.promocion', verbose_name='Promoción')),
            ],
            options={
                'db_table': 'app_negocio_producto',
            },
        ),
    ]
