# Generated by Django 5.2.12 on 2026-06-25 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cu7_gestionar_productos', '0001_initial'),
        ('customers', '0011_client_limite_alcanzado_fecha_plan_ventas_max_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('ABIERTO', 'Abierto'), ('CERRADO', 'Cerrado'), ('ABANDONADO', 'Abandonado')], default='ABIERTO', max_length=20, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carritos', to='customers.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Carrito',
                'verbose_name_plural': 'Carritos',
                'db_table': 'app_negocio_carrito',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='CarritoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1, verbose_name='Cantidad')),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Agregado')),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cu11_gestion_carrito_de_compras.carrito', verbose_name='Carrito')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='en_carritos', to='cu7_gestionar_productos.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Item del Carrito',
                'verbose_name_plural': 'Items del Carrito',
                'db_table': 'app_negocio_carrito_item',
                'ordering': ['fecha_agregado'],
                'unique_together': {('carrito', 'producto')},
            },
        ),
    ]
