from apps.customers.tenants.api.views import *
from apps.customers.tenants.api.plan_views import *
from apps.customers.users.api.views import *
from apps.customers.users.api.rol_views import *
from apps.customers.users.api.permiso_views import *
from apps.customers.users.api.device_token_views import *
from apps.customers.clientes.api.views import *
from apps.customers.audit.api.bitacora_views import *
from apps.customers.audit.api.respaldo_views import *