# Generated by Django 5.2.12 on 2026-07-20 09:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cu7_gestionar_productos', '0001_initial'),
        ('customers', '0011_client_limite_alcanzado_fecha_plan_ventas_max_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reseña',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comentario', models.TextField(blank=True, max_length=1000, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], default='APROBADA', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reseñas', to='customers.cliente')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reseñas', to='cu7_gestionar_productos.producto')),
            ],
            options={
                'verbose_name': 'Reseña de Producto',
                'verbose_name_plural': 'Reseñas',
                'db_table': 'app_negocio_resena',
                'ordering': ['-fecha_creacion'],
                'unique_together': {('producto', 'cliente')},
            },
        ),
    ]
