# Generated by Django 5.2.12 on 2026-04-11 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_bitacora_idusuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='RespaldoSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('nombre', models.CharField(max_length=100)),
                ('blob_data', models.BinaryField(help_text='Datos del respaldo comprimidos y ofuscados')),
                ('checksum', models.CharField(blank=True, max_length=64)),
                ('metadata', models.JSONField(default=dict, help_text='Información técnica del respaldo')),
            ],
            options={
                'verbose_name': 'Respaldo del Sistema',
                'verbose_name_plural': 'Respaldos del Sistema',
                'ordering': ['-timestamp'],
            },
        ),
    ]
