# Generated by Django 5.2.12 on 2026-05-10 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_client_categoria_tienda_client_descripcion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Permiso')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código Identificador')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('modulo', models.CharField(help_text='Ej: Productos, Ventas, Usuarios', max_length=50, verbose_name='Módulo al que pertenece')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Permiso',
                'verbose_name_plural': 'Permisos',
                'db_table': 'customers_permiso',
                'ordering': ['modulo', 'nombre'],
            },
        ),
        migrations.AlterModelOptions(
            name='respaldosistema',
            options={'ordering': ['timestamp'], 'verbose_name': 'Respaldo del Sistema', 'verbose_name_plural': 'Respaldos del Sistema'},
        ),
        migrations.RemoveField(
            model_name='respaldosistema',
            name='checksum',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='rol',
        ),
        migrations.AddField(
            model_name='respaldosistema',
            name='anterior',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sucesor', to='customers.respaldosistema', verbose_name='Versión Anterior (Cola)'),
        ),
        migrations.AddField(
            model_name='respaldosistema',
            name='archivo_path',
            field=models.CharField(blank=True, help_text='Ruta física en el servidor', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='respaldosistema',
            name='siguiente',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predecesor', to='customers.respaldosistema', verbose_name='Versión Siguiente'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='usuarios', to='customers.rol', verbose_name='Roles'),
        ),
        migrations.AlterField(
            model_name='respaldosistema',
            name='blob_data',
            field=models.BinaryField(blank=True, help_text='Copia de seguridad en DB (opcional)', null=True),
        ),
        migrations.AlterField(
            model_name='respaldosistema',
            name='metadata',
            field=models.JSONField(default=dict, help_text='Info técnica: tablas, tamaño, etc.'),
        ),
        migrations.AlterModelTable(
            name='respaldosistema',
            table='customers_respaldo',
        ),
        migrations.AddField(
            model_name='rol',
            name='permisos',
            field=models.ManyToManyField(blank=True, related_name='roles', to='customers.permiso', verbose_name='Permisos Asignados'),
        ),
    ]
