# Generated by Django 5.2.12 on 2026-05-25 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_alter_usuario_options_rol_tenant_devicetoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionRespaldo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=False)),
                ('frecuencia', models.CharField(choices=[('DIARIO', 'Diario'), ('SEMANAL', 'Semanal'), ('MENSUAL', 'Mensual')], default='DIARIO', max_length=10)),
                ('hora_ejecucion', models.TimeField(help_text='Hora del día (HH:MM:SS)')),
                ('dia_referencia', models.IntegerField(default=0, help_text='Día de la semana (0-6) o del mes (1-31)')),
            ],
            options={
                'verbose_name': 'Configuración de Respaldo',
                'verbose_name_plural': 'Configuraciones de Respaldo',
                'db_table': 'customers_configuracion_respaldo',
            },
        ),
    ]
