# Generated by Django 5.2.12 on 2026-05-30 22:29

import apps.customers.models.mobile_release
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_alter_rol_nombre_rol_unique_rol_nombre_per_tenant'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_type', models.CharField(choices=[('cliente', 'App Cliente'), ('vendedor', 'App Vendedor')], max_length=20, verbose_name='Tipo de App')),
                ('version', models.CharField(max_length=20, verbose_name='VersiÃ³n')),
                ('file', models.FileField(upload_to=apps.customers.models.mobile_release.release_upload_path, verbose_name='Archivo APK')),
                ('is_latest', models.BooleanField(default=False, verbose_name='Es la Ãºltima versiÃ³n')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Subida')),
            ],
            options={
                'verbose_name': 'Release MÃ³vil',
                'verbose_name_plural': 'Releases MÃ³viles',
                'db_table': 'mobile_release',
                'ordering': ['-created_at'],
            },
        ),
    ]
