# Generated by Django 5.2.12 on 2026-07-20 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0011_client_limite_alcanzado_fecha_plan_ventas_max_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaPuntos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo_actual', models.IntegerField(default=0)),
                ('puntos_historicos', models.IntegerField(default=0)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cuenta_puntos', to='customers.cliente')),
            ],
            options={
                'verbose_name': 'Cuenta de Puntos',
                'verbose_name_plural': 'Cuentas de Puntos',
                'db_table': 'app_negocio_cuenta_puntos',
            },
        ),
        migrations.CreateModel(
            name='HistorialPuntos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_operacion', models.CharField(choices=[('ACUMULACION', 'Acumulación por Compra'), ('CANJE', 'Canje por Descuento'), ('AJUSTE', 'Ajuste Manual')], max_length=20)),
                ('monto_puntos', models.IntegerField()),
                ('referencia', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='cu26_gestionar_fidelizacion.cuentapuntos')),
            ],
            options={
                'verbose_name': 'Historial de Puntos',
                'verbose_name_plural': 'Historial de Puntos',
                'db_table': 'app_negocio_historial_puntos',
                'ordering': ['-fecha'],
            },
        ),
    ]
