# Generated by Django 5.2.12 on 2026-06-25 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cu12_gestionar_metodos_de_pago', '0001_initial'),
        ('cu13_gestionar_estado_de_pedido', '0001_initial'),
        ('cu7_gestionar_productos', '0001_initial'),
        ('customers', '0011_client_limite_alcanzado_fecha_plan_ventas_max_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('nro', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='Número de Factura')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('hora', models.TimeField(auto_now_add=True, verbose_name='Hora')),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto Total')),
                ('moneda', models.CharField(default='BOB', max_length=10, verbose_name='Moneda')),
                ('cuf', models.TextField(blank=True, null=True, verbose_name='CUF (Código Único de Factura)')),
                ('estado', models.CharField(choices=[('VIGENTE', 'Vigente'), ('ANULADA', 'Anulada')], default='VIGENTE', max_length=20, verbose_name='Estado')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='facturas', to='customers.cliente', verbose_name='Cliente')),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='factura', to='cu13_gestionar_estado_de_pedido.pedido', verbose_name='Pedido')),
                ('tipo_pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas', to='cu12_gestionar_metodos_de_pago.tipopago', verbose_name='Tipo de Pago')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'db_table': 'app_negocio_factura',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='DetalleFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario')),
                ('total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total (cantidad * precio_unitario)')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='en_facturas', to='cu7_gestionar_productos.producto', verbose_name='Producto')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='cu14_generar_facturacion.factura', verbose_name='Factura')),
            ],
            options={
                'verbose_name': 'Detalle de Factura',
                'verbose_name_plural': 'Detalles de Factura',
                'db_table': 'app_negocio_detalle_factura',
                'ordering': ['factura', 'id'],
            },
        ),
    ]
