// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALMe-gdyrLdK38peZuu7pHeytDLbu9ZCU',
    appId: '1:76539049876:web:2e1fcff13448f0a851c181',
    messagingSenderId: '76539049876',
    projectId: 'si2parcial-9e9e9',
    authDomain: 'si2parcial-9e9e9.firebaseapp.com',
    storageBucket: 'si2parcial-9e9e9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6YfEqFoSld9rscnMv_BLYUT2d65r6jro',
    appId: '1:76539049876:android:670d903356b8dcdd51c181',
    messagingSenderId: '76539049876',
    projectId: 'si2parcial-9e9e9',
    storageBucket: 'si2parcial-9e9e9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9LQwvJPDbeIouPGvBnBaRMLFIUk89GlU',
    appId: '1:76539049876:ios:d0a754dd03c6709051c181',
    messagingSenderId: '76539049876',
    projectId: 'si2parcial-9e9e9',
    storageBucket: 'si2parcial-9e9e9.firebasestorage.app',
    iosBundleId: 'com.example.mcliente',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9LQwvJPDbeIouPGvBnBaRMLFIUk89GlU',
    appId: '1:76539049876:ios:d0a754dd03c6709051c181',
    messagingSenderId: '76539049876',
    projectId: 'si2parcial-9e9e9',
    storageBucket: 'si2parcial-9e9e9.firebasestorage.app',
    iosBundleId: 'com.example.mcliente',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALMe-gdyrLdK38peZuu7pHeytDLbu9ZCU',
    appId: '1:76539049876:web:127b777e9212a69451c181',
    messagingSenderId: '76539049876',
    projectId: 'si2parcial-9e9e9',
    authDomain: 'si2parcial-9e9e9.firebaseapp.com',
    storageBucket: 'si2parcial-9e9e9.firebasestorage.app',
  );

}