# Generated by Django 5.2.12 on 2026-05-08 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_negocio', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='costo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Costo de Compra'),
        ),
    ]
