# Generated by Django 5.2.12 on 2026-05-24 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_negocio', '0005_pedido_stripe_session_id_alter_pedido_estado'),
        ('customers', '0005_alter_usuario_options_rol_tenant_devicetoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('tipo', models.CharField(choices=[('PAGO', 'Pago'), ('PEDIDO', 'Pedido'), ('SISTEMA', 'Sistema')], default='SISTEMA', max_length=20)),
                ('leido', models.BooleanField(default=False, verbose_name='Leído')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='customers.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'db_table': 'app_negocio_notificacion',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
