# Generated by Django 5.2.12 on 2026-07-20 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cu7_gestionar_productos', '0001_initial'),
        ('customers', '0011_client_limite_alcanzado_fecha_plan_ventas_max_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to='customers.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Lista de Deseos',
                'verbose_name_plural': 'Listas de Deseos',
                'db_table': 'app_negocio_wishlist',
            },
        ),
        migrations.CreateModel(
            name='WishlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agregado_en', models.DateTimeField(auto_now_add=True, verbose_name='Agregado en')),
                ('notificado', models.BooleanField(default=False, help_text='True si ya se envió una notificación de bajada de precio para este item.', verbose_name='Notificado por oferta')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='en_wishlists', to='cu7_gestionar_productos.producto', verbose_name='Producto')),
                ('wishlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cu25_gestionar_wishlist.wishlist', verbose_name='Lista de Deseos')),
            ],
            options={
                'verbose_name': 'Item de Lista de Deseos',
                'verbose_name_plural': 'Items de Wishlist',
                'db_table': 'app_negocio_wishlist_item',
                'ordering': ['-agregado_en'],
                'unique_together': {('wishlist', 'producto')},
            },
        ),
    ]
